P8105: Homework \#3
================
Zachary Katz (UNI: zak2132)
10/20/2021

## Problem 1

First, we’d like to conduct some exploratory analysis of the `instacart`
dataset. Our initial step is to load the data as follows:

``` r
library(p8105.datasets)
data("instacart")
```

Before answering the questions formulated as part of Problem 1, let’s
examine the tibble in its current form and make sure it’s tidy.

``` r
# Examine head and tail of `instacart` df
head(instacart) %>% knitr::kable()
```

| order\_id | product\_id | add\_to\_cart\_order | reordered | user\_id | eval\_set | order\_number | order\_dow | order\_hour\_of\_day | days\_since\_prior\_order | product\_name                                 | aisle\_id | department\_id | aisle                | department   |
|----------:|------------:|---------------------:|----------:|---------:|:----------|--------------:|-----------:|---------------------:|--------------------------:|:----------------------------------------------|----------:|---------------:|:---------------------|:-------------|
|         1 |       49302 |                    1 |         1 |   112108 | train     |             4 |          4 |                   10 |                         9 | Bulgarian Yogurt                              |       120 |             16 | yogurt               | dairy eggs   |
|         1 |       11109 |                    2 |         1 |   112108 | train     |             4 |          4 |                   10 |                         9 | Organic 4% Milk Fat Whole Milk Cottage Cheese |       108 |             16 | other creams cheeses | dairy eggs   |
|         1 |       10246 |                    3 |         0 |   112108 | train     |             4 |          4 |                   10 |                         9 | Organic Celery Hearts                         |        83 |              4 | fresh vegetables     | produce      |
|         1 |       49683 |                    4 |         0 |   112108 | train     |             4 |          4 |                   10 |                         9 | Cucumber Kirby                                |        83 |              4 | fresh vegetables     | produce      |
|         1 |       43633 |                    5 |         1 |   112108 | train     |             4 |          4 |                   10 |                         9 | Lightly Smoked Sardines in Olive Oil          |        95 |             15 | canned meat seafood  | canned goods |
|         1 |       13176 |                    6 |         0 |   112108 | train     |             4 |          4 |                   10 |                         9 | Bag of Organic Bananas                        |        24 |              4 | fresh fruits         | produce      |

``` r
tail(instacart) %>% knitr::kable()
```

| order\_id | product\_id | add\_to\_cart\_order | reordered | user\_id | eval\_set | order\_number | order\_dow | order\_hour\_of\_day | days\_since\_prior\_order | product\_name                                                    | aisle\_id | department\_id | aisle                         | department |
|----------:|------------:|---------------------:|----------:|---------:|:----------|--------------:|-----------:|---------------------:|--------------------------:|:-----------------------------------------------------------------|----------:|---------------:|:------------------------------|:-----------|
|   3421063 |       13565 |                    2 |         1 |   169679 | train     |            30 |          0 |                   10 |                         4 | No Salt Added Gluten-Free Blue Chips Made with Organic Blue Corn |       107 |             19 | chips pretzels                | snacks     |
|   3421063 |       14233 |                    3 |         1 |   169679 | train     |            30 |          0 |                   10 |                         4 | Natural Artesian Water                                           |       115 |              7 | water seltzer sparkling water | beverages  |
|   3421063 |       35548 |                    4 |         1 |   169679 | train     |            30 |          0 |                   10 |                         4 | Twice Baked Potatoes                                             |        13 |             20 | prepared meals                | deli       |
|   3421070 |       35951 |                    1 |         1 |   139822 | train     |            15 |          6 |                   10 |                         8 | Organic Unsweetened Almond Milk                                  |        91 |             16 | soy lactosefree               | dairy eggs |
|   3421070 |       16953 |                    2 |         1 |   139822 | train     |            15 |          6 |                   10 |                         8 | Creamy Peanut Butter                                             |        88 |             13 | spreads                       | pantry     |
|   3421070 |        4724 |                    3 |         1 |   139822 | train     |            15 |          6 |                   10 |                         8 | Broccoli Florettes                                               |        32 |              4 | packaged produce              | produce    |

``` r
# Examine structure, summary, and skim
str(instacart)
```

    ## tibble [1,384,617 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ order_id              : int [1:1384617] 1 1 1 1 1 1 1 1 36 36 ...
    ##  $ product_id            : int [1:1384617] 49302 11109 10246 49683 43633 13176 47209 22035 39612 19660 ...
    ##  $ add_to_cart_order     : int [1:1384617] 1 2 3 4 5 6 7 8 1 2 ...
    ##  $ reordered             : int [1:1384617] 1 1 0 0 1 0 0 1 0 1 ...
    ##  $ user_id               : int [1:1384617] 112108 112108 112108 112108 112108 112108 112108 112108 79431 79431 ...
    ##  $ eval_set              : chr [1:1384617] "train" "train" "train" "train" ...
    ##  $ order_number          : int [1:1384617] 4 4 4 4 4 4 4 4 23 23 ...
    ##  $ order_dow             : int [1:1384617] 4 4 4 4 4 4 4 4 6 6 ...
    ##  $ order_hour_of_day     : int [1:1384617] 10 10 10 10 10 10 10 10 18 18 ...
    ##  $ days_since_prior_order: int [1:1384617] 9 9 9 9 9 9 9 9 30 30 ...
    ##  $ product_name          : chr [1:1384617] "Bulgarian Yogurt" "Organic 4% Milk Fat Whole Milk Cottage Cheese" "Organic Celery Hearts" "Cucumber Kirby" ...
    ##  $ aisle_id              : int [1:1384617] 120 108 83 83 95 24 24 21 2 115 ...
    ##  $ department_id         : int [1:1384617] 16 16 4 4 15 4 4 16 16 7 ...
    ##  $ aisle                 : chr [1:1384617] "yogurt" "other creams cheeses" "fresh vegetables" "fresh vegetables" ...
    ##  $ department            : chr [1:1384617] "dairy eggs" "dairy eggs" "produce" "produce" ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   order_id = col_integer(),
    ##   ..   product_id = col_integer(),
    ##   ..   add_to_cart_order = col_integer(),
    ##   ..   reordered = col_integer(),
    ##   ..   user_id = col_integer(),
    ##   ..   eval_set = col_character(),
    ##   ..   order_number = col_integer(),
    ##   ..   order_dow = col_integer(),
    ##   ..   order_hour_of_day = col_integer(),
    ##   ..   days_since_prior_order = col_integer(),
    ##   ..   product_name = col_character(),
    ##   ..   aisle_id = col_integer(),
    ##   ..   department_id = col_integer(),
    ##   ..   aisle = col_character(),
    ##   ..   department = col_character()
    ##   .. )

``` r
summary(instacart)
```

    ##     order_id         product_id    add_to_cart_order   reordered     
    ##  Min.   :      1   Min.   :    1   Min.   : 1.000    Min.   :0.0000  
    ##  1st Qu.: 843370   1st Qu.:13380   1st Qu.: 3.000    1st Qu.:0.0000  
    ##  Median :1701880   Median :25298   Median : 7.000    Median :1.0000  
    ##  Mean   :1706298   Mean   :25556   Mean   : 8.758    Mean   :0.5986  
    ##  3rd Qu.:2568023   3rd Qu.:37940   3rd Qu.:12.000    3rd Qu.:1.0000  
    ##  Max.   :3421070   Max.   :49688   Max.   :80.000    Max.   :1.0000  
    ##     user_id         eval_set          order_number      order_dow    
    ##  Min.   :     1   Length:1384617     Min.   :  4.00   Min.   :0.000  
    ##  1st Qu.: 51732   Class :character   1st Qu.:  6.00   1st Qu.:1.000  
    ##  Median :102933   Mode  :character   Median : 11.00   Median :3.000  
    ##  Mean   :103113                      Mean   : 17.09   Mean   :2.701  
    ##  3rd Qu.:154959                      3rd Qu.: 21.00   3rd Qu.:5.000  
    ##  Max.   :206209                      Max.   :100.00   Max.   :6.000  
    ##  order_hour_of_day days_since_prior_order product_name          aisle_id    
    ##  Min.   : 0.00     Min.   : 0.00          Length:1384617     Min.   :  1.0  
    ##  1st Qu.:10.00     1st Qu.: 7.00          Class :character   1st Qu.: 31.0  
    ##  Median :14.00     Median :15.00          Mode  :character   Median : 83.0  
    ##  Mean   :13.58     Mean   :17.07                             Mean   : 71.3  
    ##  3rd Qu.:17.00     3rd Qu.:30.00                             3rd Qu.:107.0  
    ##  Max.   :23.00     Max.   :30.00                             Max.   :134.0  
    ##  department_id      aisle            department       
    ##  Min.   : 1.00   Length:1384617     Length:1384617    
    ##  1st Qu.: 4.00   Class :character   Class :character  
    ##  Median : 8.00   Mode  :character   Mode  :character  
    ##  Mean   : 9.84                                        
    ##  3rd Qu.:16.00                                        
    ##  Max.   :21.00

``` r
skimr::skim(instacart)
```

|                                                  |           |
|:-------------------------------------------------|:----------|
| Name                                             | instacart |
| Number of rows                                   | 1384617   |
| Number of columns                                | 15        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |           |
| Column type frequency:                           |           |
| character                                        | 4         |
| numeric                                          | 11        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |           |
| Group variables                                  | None      |

Data summary

**Variable type: character**

| skim\_variable | n\_missing | complete\_rate | min | max | empty | n\_unique | whitespace |
|:---------------|-----------:|---------------:|----:|----:|------:|----------:|-----------:|
| eval\_set      |          0 |              1 |   5 |   5 |     0 |         1 |          0 |
| product\_name  |          0 |              1 |   3 | 159 |     0 |     39123 |          0 |
| aisle          |          0 |              1 |   3 |  29 |     0 |       134 |          0 |
| department     |          0 |              1 |   4 |  15 |     0 |        21 |          0 |

**Variable type: numeric**

| skim\_variable            | n\_missing | complete\_rate |       mean |        sd |  p0 |    p25 |     p50 |     p75 |    p100 | hist  |
|:--------------------------|-----------:|---------------:|-----------:|----------:|----:|-------:|--------:|--------:|--------:|:------|
| order\_id                 |          0 |              1 | 1706297.62 | 989732.65 |   1 | 843370 | 1701880 | 2568023 | 3421070 | ▇▇▇▇▇ |
| product\_id               |          0 |              1 |   25556.24 |  14121.27 |   1 |  13380 |   25298 |   37940 |   49688 | ▆▆▇▆▇ |
| add\_to\_cart\_order      |          0 |              1 |       8.76 |      7.42 |   1 |      3 |       7 |      12 |      80 | ▇▁▁▁▁ |
| reordered                 |          0 |              1 |       0.60 |      0.49 |   0 |      0 |       1 |       1 |       1 | ▆▁▁▁▇ |
| user\_id                  |          0 |              1 |  103112.78 |  59487.15 |   1 |  51732 |  102933 |  154959 |  206209 | ▇▇▇▇▇ |
| order\_number             |          0 |              1 |      17.09 |     16.61 |   4 |      6 |      11 |      21 |     100 | ▇▂▁▁▁ |
| order\_dow                |          0 |              1 |       2.70 |      2.17 |   0 |      1 |       3 |       5 |       6 | ▇▂▂▂▆ |
| order\_hour\_of\_day      |          0 |              1 |      13.58 |      4.24 |   0 |     10 |      14 |      17 |      23 | ▁▃▇▇▃ |
| days\_since\_prior\_order |          0 |              1 |      17.07 |     10.43 |   0 |      7 |      15 |      30 |      30 | ▅▅▃▂▇ |
| aisle\_id                 |          0 |              1 |      71.30 |     38.10 |   1 |     31 |      83 |     107 |     134 | ▆▃▃▇▆ |
| department\_id            |          0 |              1 |       9.84 |      6.29 |   1 |      4 |       8 |      16 |      21 | ▇▂▂▅▂ |

Instacart is an online service that allows grocery shopping from local
stores. This data frame represents 1384617 observations, where each row
in the tibble is a product from a given user’s order. This dataset has
already been cleaned such that there is only one order per user included
here. In total, this data contains product order information for 131209
unique users.

For each observation, 15 variables are represented; our examination of
the data set above indicates that there are no missing values. The full
set of variables included is: order\_id, product\_id,
add\_to\_cart\_order, reordered, user\_id, eval\_set, order\_number,
order\_dow, order\_hour\_of\_day, days\_since\_prior\_order,
product\_name, aisle\_id, department\_id, aisle, department. Each of
these variables operates as follows:

`order_id`, `product_id`, `user_id`, `product_name`, `department_id`,
`department`, `aisle_id`, and `aisle` are identifiers of the order,
product, product’s department, and user. `add_to_cart_order`,
`order_number`, `order_dow`, `order_hour_of_day`,
`days_since_prior_order` indicate when orders were placed in the cart
and ordered both absolutely in time and relative to other orders.
`reordered` is an indicator that is 1 if a product has been ordered by
the user in the past, while `eval_set` indicates that all orders in this
data set are part of the “train” evaluation set.

Let’s clean our tibble to be a bit clearer:

``` r
instacart = instacart %>% 
      # Remove and rearrange certain columns
      select(-eval_set) %>% 
      select (order_id, product_id, user_id, everything()) %>% 
      # Recode certain variables
      mutate(reordered = as.logical(reordered),
             order_dow = wday(order_dow))
```

Now, we can start answer the following questions:

#### How many aisles are there, and which aisles are the most items ordered from?

To determine the number of unique aisles, we calculate as follows:

``` r
num_aisles = length(unique(pull(instacart, aisle)))
```

There are 134 in total.

Now, let’s see which ones have the most items ordered from them. To
determine the aisles with the most items ordered from them, we want to
sort the aisles in descending order of observations in that aisle.

``` r
# Group by aisle and summarize number of observations in descending order
orders_by_aisle = instacart %>% 
      group_by(aisle) %>% 
      summarize(n_obs = n()) %>% 
      arrange(desc(n_obs)) 

# Check out the top 5 aisles by number of observations in table form
orders_by_aisle %>% 
      head(5) %>% 
      knitr::kable()
```

| aisle                      | n\_obs |
|:---------------------------|-------:|
| fresh vegetables           | 150609 |
| fresh fruits               | 150473 |
| packaged vegetables fruits |  78493 |
| yogurt                     |  55240 |
| packaged cheese            |  41699 |

From the table, we can tell that fresh vegetables and fresh fruits are
the two aisles with the most items ordered, with over 150,000
observations each.

We can create a plot to show the number of items ordered in each aisle,
limited to aisles with more than 10,000 items ordered.

``` r
orders_by_aisle %>% 
      # Filter observations
      filter(n_obs > 10000) %>% 
      # Relevel aisles as factor by number of observations
      mutate(aisle = forcats::fct_reorder(aisle, n_obs)) %>% 
      ggplot(aes(
            x = aisle,
            y = n_obs)
      ) + 
      geom_bar(stat = "identity") + 
      # Flip X and Y axes
      coord_flip() + 
      # Label graph
      labs(
            title = "Number of items ordered per aisle",
            y = "Number of items ordered",
            x = "Product aisle",
            caption = "Note: only includes aisles with >10K items ordered"
      )
```

<img src="p8105_hw3_zak2132_files/figure-gfm/create plot of number of items ordered by aisle-1.png" width="90%" />

Additionally, we’d like to create a table showing the three most popular
items in each of the following aisles: “baking ingredients,” “dog food
care,” and “packaged vegetables fruits.” We should also include in our
table the number of times each item is ordered.

``` r
instacart %>% 
      # Filter for appropriate aisles and group by aisle and product name
      filter(aisle == "baking ingredients" | aisle == "dog food care" | aisle == "packaged vegetables fruits") %>% 
      group_by(aisle, product_name) %>% 
      summarize(n_obs = n()) %>% 
      # Determine rank for product in each aisle by number of observations
      mutate(
            product_rank = min_rank(desc(n_obs))
      ) %>% 
      filter(product_rank < 4) %>% 
      # Arrange table by aisle and then product rank by # of obs
      arrange(aisle, product_rank) %>% 
      rename(num_orders = n_obs) %>% 
      knitr::kable()
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the `.groups` argument.

| aisle                      | product\_name                                 | num\_orders | product\_rank |
|:---------------------------|:----------------------------------------------|------------:|--------------:|
| baking ingredients         | Light Brown Sugar                             |         499 |             1 |
| baking ingredients         | Pure Baking Soda                              |         387 |             2 |
| baking ingredients         | Cane Sugar                                    |         336 |             3 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |          30 |             1 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |          28 |             2 |
| dog food care              | Small Dog Biscuits                            |          26 |             3 |
| packaged vegetables fruits | Organic Baby Spinach                          |        9784 |             1 |
| packaged vegetables fruits | Organic Raspberries                           |        5546 |             2 |
| packaged vegetables fruits | Organic Blueberries                           |        4966 |             3 |

Finally, let’s create a table showing the mean hour of the day at which
Pink Lady Apples and Coffee Ice Cream are ordered on each day of the
week.
